### ISSUE TITLE
Ged rid of ExAws

### ISSUE THREAD

**Issue by fuelen** [elixir-capsule/supplement#3]
Hello
I found that current S3 module uses ExAws.
There is a recommendation to use aws-beam/aws-elixir instead. Read more here
https://elixirforum.com/t/contributing-to-aws-beam-aws-elixir/34150

**Comment by tfwright** [comment]
Hi! I have been following that discussion. I actually tried to use that library first, but ran into a couple of problems. 

First, there was no way to override the endpoint, so it couldn't be used with Digital Ocean Spaces, which I need to do. I worked a bit on a workaround for that here: https://github.com/aws-beam/aws-codegen/issues/49

But second, when testing that workaround, I couldn't get various basic S3 functions to work. See https://github.com/aws-beam/aws-elixir/issues/41

So it seems we are a bit of a ways from being able to drop in aws-beam as a replacement for ExAws. As soon as the above issues are resolved, however, I do plan to swap it out.
