### ISSUE TITLE
Override global configs

### ISSUE THREAD

**Issue by fuelen** [elixir-capsule/supplement#4]
https://github.com/elixir-capsule/supplement/blob/0f2f800f9ff07ec8b0e1a2c8a76a1df210e35d9a/lib/supplement/storages/s3.ex#L10
it would be great to have an ability to override global configs to have an ability to use different credentials for different types of files.

**Comment by tfwright** [comment]
Hmm, overriding the bucket in the line you've excerpted would be trivial, and clearly useful.

I'm less sure about "credentials" though. Do you mean using different account keys/secrets?

**Comment by fuelen** [comment]
Yes, currently in ExAws you can override any attribute right before sending.

**Comment by tfwright** [comment]
I think that is going to require some changes to the API, since it wouldn't make sense for something like that to be possible only on the `put` callback. Do you have any thoughts on that? Just make it one of the opts, and extend the behavior of all the callbacks to take that arg?

**Comment by fuelen** [comment]
> Do you have any thoughts on that?

Unfortunately, no

**Comment by tfwright** [comment]
I added support for overriding global options and specifically the bucket. I couldn't find any good documentation on overriding account credentials. It also seems like something that could be done outside of the storage module if necessary, so I'm going to table that for now, to revisit if/when I can switch out the s3 client library.
